apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: nginx-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
