apiVersion: v1
kind: ServiceAccount
metadata:
  name: popeye
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: popeye
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "nodes", "namespaces", "limitranges", "persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: popeye
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: popeye
subjects:
- kind: ServiceAccount
  name: popeye
  namespace: dev
