apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  selector:
    app: nginx-exporter
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics 